name: Nightly Build & Check

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  push:
    branches: [ "main", "2.x" ]
  pull_request:
    branches: [ "main", "2.x" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      # - name: Run Tests
      #   run: pnpm test

      - name: Build
        run: pnpm run build
